spring:
  application:
    name: msclientes

server:
  port: 0   # o 0 faz ele buildar em uma porta randomica

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
